// HeriTech — Mock Data Fixtures
// Seed data for all Asian festivals spanning West to East Asia.
// Replace fetch functions with real API calls in production.

import type {
  Festival,
  MaterialBatch,
  Product,
  LeaderboardEntry,
  NgoDisbursement,
  ReleaseAgreement,
  User,
} from "./types";

// ─── FESTIVALS ────────────────────────────────────────────────────────────────

export const FESTIVALS: Festival[] = [
  {
    id: "f-nowruz",
    name: "Nowruz",
    country: "Turkey",
    city: "Istanbul",
    dates: "March 21, 2026",
    materialType: "Floral / Organic",
    estimatedWasteKg: 12000,
    gps: { lat: 41.0082, lng: 28.9784 },
    description: "Persian New Year floral and herbal arrangements",
    emoji: "🌸",
  },
  {
    id: "f-ganesh",
    name: "Ganesh Chaturthi",
    country: "India",
    city: "Mumbai",
    dates: "Aug 27 – Sep 5, 2026",
    materialType: "Floral / Organic",
    estimatedWasteKg: 150000,
    gps: { lat: 19.076, lng: 72.8777 },
    description: "Nirmalaya floral waste from temple offerings and idol immersion",
    emoji: "🪷",
  },
  {
    id: "f-yipeng",
    name: "Yi Peng",
    country: "Thailand",
    city: "Chiang Mai",
    dates: "Nov 24–25, 2026",
    materialType: "Bamboo",
    estimatedWasteKg: 8500,
    gps: { lat: 18.7883, lng: 98.9853 },
    description: "Sky lantern bamboo frames and rice paper after the lantern release",
    emoji: "🏮",
  },
  {
    id: "f-pingxi",
    name: "Pingxi Sky Lantern Festival",
    country: "Taiwan",
    city: "Pingxi",
    dates: "March 3, 2026",
    materialType: "Rice Paper",
    estimatedWasteKg: 4200,
    gps: { lat: 25.0168, lng: 121.5717 },
    description: "Rice paper and bamboo wire lantern remnants collected post-release",
    emoji: "🕯️",
  },
  {
    id: "f-balikite",
    name: "Bali Kite Festival",
    country: "Indonesia",
    city: "Sanur, Bali",
    dates: "Jul 1–3, 2026",
    materialType: "Cotton Cloth",
    estimatedWasteKg: 3100,
    gps: { lat: -8.6908, lng: 115.2627 },
    description: "Traditional bamboo-framed kites with cotton cloth skins from competition",
    emoji: "🪁",
  },
  {
    id: "f-panagbenga",
    name: "Panagbenga Festival",
    country: "Philippines",
    city: "Baguio",
    dates: "February 2026",
    materialType: "Floral / Organic",
    estimatedWasteKg: 6800,
    gps: { lat: 16.4023, lng: 120.596 },
    description: "Cut flowers and parade floats — a month-long flower festival",
    emoji: "🌺",
  },
  {
    id: "f-aomori",
    name: "Aomori Nebuta Matsuri",
    country: "Japan",
    city: "Aomori",
    dates: "Aug 2–7, 2026",
    materialType: "Rice Paper",
    estimatedWasteKg: 5600,
    gps: { lat: 40.8246, lng: 140.74 },
    description: "Illuminated paper and wood effigy parade floats after festival",
    emoji: "🎆",
  },
];

// ─── USERS ────────────────────────────────────────────────────────────────────

export const MOCK_USERS: User[] = [
  {
    id: "usr-lgu-001",
    name: "Officer Malee Sriwan",
    role: "lgu",
    stationName: "Chiang Mai Heritage Station",
    avatarUrl: undefined,
  },
  {
    id: "usr-art-001",
    name: "Artisan Priya Mehta",
    role: "artisan",
    workshopName: "Lotus Craft Studio",
    verifiedArtisan: true,
    avatarUrl: undefined,
  },
  {
    id: "usr-buy-001",
    name: "Buyer Alex Chen",
    role: "buyer",
    avatarUrl: undefined,
  },
];

// ─── RELEASE AGREEMENTS ───────────────────────────────────────────────────────

export const RELEASE_AGREEMENTS: ReleaseAgreement[] = [
  {
    id: "RA-2026-001",
    title: "Yi Peng Lantern Waste Collection Agreement",
    status: "active",
    allocatedKg: 8500,
    collectedKg: 6230,
    festival: "Yi Peng",
    country: "Thailand",
    organizerName: "Chiang Mai Municipality",
    signedAt: "2026-11-01T08:00:00Z",
  },
  {
    id: "RA-2026-002",
    title: "Ganesh Chaturthi Nirmalaya Collection",
    status: "active",
    allocatedKg: 150000,
    collectedKg: 48500,
    festival: "Ganesh Chaturthi",
    country: "India",
    organizerName: "Thane Municipal Corporation",
    signedAt: "2026-08-01T08:00:00Z",
  },
  {
    id: "RA-2026-003",
    title: "Pingxi Lantern Festival Material Recovery",
    status: "closed",
    allocatedKg: 4200,
    collectedKg: 4200,
    festival: "Pingxi Sky Lantern Festival",
    country: "Taiwan",
    organizerName: "New Taipei City Government",
    signedAt: "2026-02-15T08:00:00Z",
  },
  {
    id: "RA-2026-004",
    title: "Bali Kite Festival Textile Recovery",
    status: "active",
    allocatedKg: 3100,
    collectedKg: 1850,
    festival: "Bali Kite Festival",
    country: "Indonesia",
    organizerName: "Sanur Cultural Committee",
    signedAt: "2026-06-10T08:00:00Z",
  },
  {
    id: "RA-2026-005",
    title: "Aomori Nebuta Float Deconstruction",
    status: "active",
    allocatedKg: 5600,
    collectedKg: 3200,
    festival: "Aomori Nebuta Matsuri",
    country: "Japan",
    organizerName: "Aomori Nebuta Festival Executive Committee",
    signedAt: "2026-07-20T08:00:00Z",
  },
];

// ─── MATERIAL BATCHES ─────────────────────────────────────────────────────────

export const MATERIAL_BATCHES: MaterialBatch[] = [
  {
    id: "HT-2026-8891",
    title: "Yi Peng Lantern Bamboo Scaffolding",
    materialType: "Bamboo",
    weightKg: 47,
    condition: "Good",
    status: "available",
    gps: { lat: 18.7883, lng: 98.9853 },
    scannedByOfficerId: "usr-lgu-001",
    releaseAgreementId: "RA-2026-001",
    createdAt: "2026-11-25T06:30:00Z",
    txHash: "a3f8c2e1d4b7a9f0e2c5b8d1a4f7c0e3b6a9d2f5c8b1e4a7d0f3c6b9e2a5d8f1",
    festival: "Yi Peng",
    country: "Thailand",
    aiInferredMaterial: "Bamboo",
    aiInferredCondition: "Good",
    aiConfidence: 0.94,
  },
  {
    id: "HT-2026-8892",
    title: "Ganesh Chaturthi Nirmalaya Flowers",
    materialType: "Floral / Organic",
    weightKg: 120,
    condition: "Fair",
    status: "reserved",
    gps: { lat: 19.076, lng: 72.8777 },
    scannedByOfficerId: "usr-lgu-001",
    reservedByArtisanId: "usr-art-001",
    releaseAgreementId: "RA-2026-002",
    createdAt: "2026-09-01T07:15:00Z",
    txHash: "b4a9d3e6f2c8b5a1d7e4f0c3b9a6d2e8f5c1b7a3d6e9f2c5b8a4d1e7f3c0b6a9",
    festival: "Ganesh Chaturthi",
    country: "India",
    aiInferredMaterial: "Floral / Organic",
    aiInferredCondition: "Fair",
    aiConfidence: 0.88,
  },
  {
    id: "HT-2026-7734",
    title: "Pingxi Rice Paper Lantern Remnants",
    materialType: "Rice Paper",
    weightKg: 28,
    condition: "Excellent",
    status: "available",
    gps: { lat: 25.0168, lng: 121.5717 },
    scannedByOfficerId: "usr-lgu-001",
    releaseAgreementId: "RA-2026-003",
    createdAt: "2026-03-04T05:45:00Z",
    txHash: "c5b0e4f7a3d9c6b2e8f1a4d0c7b3e9f5a2d6c9b5e1f4a7d3c0b6e2f8a5d1c4b7",
    festival: "Pingxi Sky Lantern Festival",
    country: "Taiwan",
    aiInferredMaterial: "Rice Paper",
    aiInferredCondition: "Excellent",
    aiConfidence: 0.97,
  },
  {
    id: "HT-2026-5521",
    title: "Bali Kite Cotton Cloth & Bamboo",
    materialType: "Cotton Cloth",
    weightKg: 34,
    condition: "Good",
    status: "claimed",
    gps: { lat: -8.6908, lng: 115.2627 },
    scannedByOfficerId: "usr-lgu-001",
    reservedByArtisanId: "usr-art-001",
    claimedByArtisanId: "usr-art-001",
    releaseAgreementId: "RA-2026-004",
    createdAt: "2026-07-04T09:00:00Z",
    txHash: "d6c1f5a8b4e0d7c3f9a6b2e5d8c4f1a7b3e6d9c5f2b8a4d0c7f3b9e6a2d5c8f4",
    festival: "Bali Kite Festival",
    country: "Indonesia",
    aiInferredMaterial: "Cotton Cloth",
    aiInferredCondition: "Good",
    aiConfidence: 0.91,
  },
  {
    id: "HT-2026-9901",
    title: "Aomori Nebuta Rice Paper Float Sections",
    materialType: "Rice Paper",
    weightKg: 65,
    condition: "Good",
    status: "available",
    gps: { lat: 40.8246, lng: 140.74 },
    scannedByOfficerId: "usr-lgu-001",
    releaseAgreementId: "RA-2026-005",
    createdAt: "2026-08-08T04:20:00Z",
    txHash: "e7d2a6b9c5f1e8d4a0c7b3f6e2d9a5c8b4f0e7d3a9c6b2f5e1d8a4c1b7f3e0d6",
    festival: "Aomori Nebuta Matsuri",
    country: "Japan",
    aiInferredMaterial: "Rice Paper",
    aiInferredCondition: "Good",
    aiConfidence: 0.92,
  },
  {
    id: "HT-2026-3312",
    title: "Panagbenga Cut Flowers & Stems",
    materialType: "Floral / Organic",
    weightKg: 89,
    condition: "Fair",
    status: "available",
    gps: { lat: 16.4023, lng: 120.596 },
    scannedByOfficerId: "usr-lgu-001",
    releaseAgreementId: "RA-2026-001",
    createdAt: "2026-02-15T10:30:00Z",
    txHash: "f8e3b7a0c6d2f9e5b1a8d4c0f7e3b6a2d5c9f2e8b4a1d7c3f0e6b2a9d5c2f8e4",
    festival: "Panagbenga Festival",
    country: "Philippines",
    aiInferredMaterial: "Floral / Organic",
    aiInferredCondition: "Fair",
    aiConfidence: 0.85,
  },
  {
    id: "HT-2026-1145",
    title: "Nowruz Haft-Seen Herbal Arrangements",
    materialType: "Floral / Organic",
    weightKg: 42,
    condition: "Excellent",
    status: "reserved",
    gps: { lat: 41.0082, lng: 28.9784 },
    scannedByOfficerId: "usr-lgu-001",
    reservedByArtisanId: "usr-art-001",
    releaseAgreementId: "RA-2026-001",
    createdAt: "2026-03-22T09:00:00Z",
    txHash: "a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8a9b0c1d2e3f4a5b6c7d8e9f0a1b2",
    festival: "Nowruz",
    country: "Turkey",
    aiInferredMaterial: "Floral / Organic",
    aiInferredCondition: "Excellent",
    aiConfidence: 0.96,
  },
];

// ─── PRODUCTS ─────────────────────────────────────────────────────────────────

export const PRODUCTS: Product[] = [
  {
    id: "prod-001",
    title: "Yi Peng Lantern Bamboo Bowl",
    description:
      "Hand-turned from reclaimed Yi Peng lantern bamboo scaffolding. Each bowl carries a unique grain pattern from its festival origin. Comes with a HeriTech Verified Impact Pass.",
    price: 48,
    images: [],
    artisanId: "usr-art-001",
    artisanName: "Priya Mehta",
    sourceBatchId: "HT-2026-8891",
    materialTags: ["Bamboo", "Yi Peng", "Thailand"],
    stock: 12,
    split: {
      artisanPct: 70,
      platformPct: 20,
      ngoPct: 10,
      ngoFundName: "Thai River Conservation Fund",
    },
    festival: "Yi Peng",
    country: "Thailand",
    kgDiverted: 0.8,
  },
  {
    id: "prod-002",
    title: "Pingxi Lantern Paper Lampshade",
    description:
      "Crafted from recovered Pingxi Sky Lantern rice paper. The thin, translucent paper creates a warm glow perfect for ambient lighting. Zero-waste, 100% traced.",
    price: 65,
    images: [],
    artisanId: "usr-art-001",
    artisanName: "Priya Mehta",
    sourceBatchId: "HT-2026-7734",
    materialTags: ["Rice Paper", "Pingxi", "Taiwan"],
    stock: 7,
    split: {
      artisanPct: 70,
      platformPct: 20,
      ngoPct: 10,
      ngoFundName: "Taiwan Greening Initiative",
    },
    festival: "Pingxi Sky Lantern Festival",
    country: "Taiwan",
    kgDiverted: 0.5,
  },
  {
    id: "prod-003",
    title: "Bali Kite Tote Bag",
    description:
      "Upcycled from competition-grade cotton kite cloth collected after the Bali Kite Festival. Strong, lightweight, and ethically made by Balinese artisans.",
    price: 38,
    images: [],
    artisanId: "usr-art-001",
    artisanName: "Priya Mehta",
    sourceBatchId: "HT-2026-5521",
    materialTags: ["Cotton Cloth", "Bali", "Indonesia"],
    stock: 20,
    split: {
      artisanPct: 70,
      platformPct: 20,
      ngoPct: 10,
      ngoFundName: "Bali Ocean Cleanup",
    },
    festival: "Bali Kite Festival",
    country: "Indonesia",
    kgDiverted: 0.4,
  },
  {
    id: "prod-004",
    title: "Aomori Nebuta Paper Wall Art",
    description:
      "Panels salvaged from Aomori Nebuta parade floats, reframed as striking wall art. Each piece preserves the vibrant pigments and hand-brushed calligraphy of the original float.",
    price: 95,
    images: [],
    artisanId: "usr-art-001",
    artisanName: "Kenji Yamamoto",
    sourceBatchId: "HT-2026-9901",
    materialTags: ["Rice Paper", "Nebuta", "Japan"],
    stock: 4,
    split: {
      artisanPct: 70,
      platformPct: 20,
      ngoPct: 10,
      ngoFundName: "Japan Forest Restoration Fund",
    },
    festival: "Aomori Nebuta Matsuri",
    country: "Japan",
    kgDiverted: 1.2,
  },
  {
    id: "prod-005",
    title: "Ganesh Floral Incense Kit",
    description:
      "Made using the Phool.co method — Ganesh Chaturthi nirmalaya flowers sun-dried and hand-rolled into incense sticks. A verified zero-river-pollution product.",
    price: 22,
    images: [],
    artisanId: "usr-art-001",
    artisanName: "Riya Sharma",
    sourceBatchId: "HT-2026-8892",
    materialTags: ["Floral / Organic", "Ganesh Chaturthi", "India"],
    stock: 35,
    split: {
      artisanPct: 70,
      platformPct: 20,
      ngoPct: 10,
      ngoFundName: "Ganga River Clean Trust",
    },
    festival: "Ganesh Chaturthi",
    country: "India",
    kgDiverted: 0.3,
  },
  {
    id: "prod-006",
    title: "Panagbenga Pressed Flower Frame",
    description:
      "Baguio's famous festival blooms pressed and arranged in a sustainable eucalyptus frame. Each frame is unique — no two festivals bloom the same way.",
    price: 42,
    images: [],
    artisanId: "usr-art-001",
    artisanName: "Maria Santos",
    sourceBatchId: "HT-2026-3312",
    materialTags: ["Floral / Organic", "Panagbenga", "Philippines"],
    stock: 15,
    split: {
      artisanPct: 70,
      platformPct: 20,
      ngoPct: 10,
      ngoFundName: "Philippine Coral Reef Fund",
    },
    festival: "Panagbenga Festival",
    country: "Philippines",
    kgDiverted: 0.6,
  },
];

// ─── LEADERBOARD ──────────────────────────────────────────────────────────────

export const LEADERBOARD: LeaderboardEntry[] = [
  {
    userId: "usr-buy-001",
    name: "Alex Chen",
    kgDiverted: 12.4,
    itemsPurchased: 8,
    rank: 1,
    role: "buyer",
  },
  {
    userId: "usr-buy-002",
    name: "Fatima Al-Rashid",
    kgDiverted: 9.8,
    itemsPurchased: 6,
    rank: 2,
    role: "buyer",
  },
  {
    userId: "usr-buy-003",
    name: "Haruto Tanaka",
    kgDiverted: 7.2,
    itemsPurchased: 5,
    rank: 3,
    role: "buyer",
  },
  {
    userId: "usr-buy-004",
    name: "Sia Parata",
    kgDiverted: 5.5,
    itemsPurchased: 4,
    rank: 4,
    role: "buyer",
  },
  {
    userId: "usr-buy-005",
    name: "Mei-Ling Wu",
    kgDiverted: 3.9,
    itemsPurchased: 3,
    rank: 5,
    role: "buyer",
  },
];

export const ARTISAN_LEADERBOARD: LeaderboardEntry[] = [
  {
    userId: "usr-art-001",
    name: "Priya Mehta",
    kgDiverted: 284,
    itemsListed: 42,
    rank: 1,
    role: "artisan",
  },
  {
    userId: "usr-art-002",
    name: "Kenji Yamamoto",
    kgDiverted: 196,
    itemsListed: 28,
    rank: 2,
    role: "artisan",
  },
  {
    userId: "usr-art-003",
    name: "Riya Sharma",
    kgDiverted: 158,
    itemsListed: 24,
    rank: 3,
    role: "artisan",
  },
  {
    userId: "usr-art-004",
    name: "Maria Santos",
    kgDiverted: 132,
    itemsListed: 19,
    rank: 4,
    role: "artisan",
  },
  {
    userId: "usr-art-005",
    name: "Ahmad Rizki",
    kgDiverted: 98,
    itemsListed: 14,
    rank: 5,
    role: "artisan",
  },
];

// ─── NGO DISBURSEMENTS ────────────────────────────────────────────────────────

export const NGO_DISBURSEMENTS: NgoDisbursement[] = [
  {
    id: "ngo-001",
    ngoName: "Thai River Conservation Fund",
    amount: 1240,
    date: "2026-11-28T00:00:00Z",
    txHash: "a3f8c2e1d4b7a9f0e2c5b8d1a4f7c0e3",
    festival: "Yi Peng",
  },
  {
    id: "ngo-002",
    ngoName: "Ganga River Clean Trust",
    amount: 2850,
    date: "2026-09-10T00:00:00Z",
    txHash: "b4a9d3e6f2c8b5a1d7e4f0c3b9a6d2e8",
    festival: "Ganesh Chaturthi",
  },
  {
    id: "ngo-003",
    ngoName: "Taiwan Greening Initiative",
    amount: 680,
    date: "2026-03-10T00:00:00Z",
    txHash: "c5b0e4f7a3d9c6b2e8f1a4d0c7b3e9f5",
    festival: "Pingxi Sky Lantern Festival",
  },
  {
    id: "ngo-004",
    ngoName: "Bali Ocean Cleanup",
    amount: 920,
    date: "2026-07-15T00:00:00Z",
    txHash: "d6c1f5a8b4e0d7c3f9a6b2e5d8c4f1a7",
    festival: "Bali Kite Festival",
  },
  {
    id: "ngo-005",
    ngoName: "Japan Forest Restoration Fund",
    amount: 1890,
    date: "2026-08-10T00:00:00Z",
    txHash: "e7d2a6b9c5f1e8d4a0c7b3f6e2d9a5c8",
    festival: "Aomori Nebuta Matsuri",
  },
];

// ─── GLOBAL IMPACT STATS ──────────────────────────────────────────────────────

export const GLOBAL_STATS = {
  totalKgDiverted: 28430,
  totalArtisans: 147,
  totalProducts: 892,
  totalOrders: 3241,
  totalNgoDonated: 58620,
  festivalsActive: 7,
  countriesReached: 7,
};
